version: 1

jobs:
        build: 
                working_directory: ~/2020_Arduino_PI_IOT_Project
                docker:
                  -  image: circleci/python:3.9.0
                steps: 
                  - checkout
                  - run: sudo chown -R circleci:circleci /usr/local/bin
                  - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
                  - run:
                          name: Building Environment
                          command: |
                                sudo ./install_dependencies.sh
                  - run: 
                          name: Running Tests
                          command: |
                                python3 -m pytest -r flask_webapp/tests --html=flask_webapp/test-reports/report.html --self-contained-html
                  - store_test_results:
                          path: flask_webapp/test-reports/
                  - store_artifacts:
                          path: flask_webapp/test-reports/
                          destination: IOT_Flask_App

                          

