from db import db

class ScanDeviceModel(db.Model):
    __tablename__ = 'scan_devices'

    id = db.Column(db.Integer, primary_key=True)
    #datetime = Column(db.DateTime, default=datetime.now, nullable=False)
    name = db.Column(db.String(80))

    def __init__(self, name):
        # Note the id is auto generated by the SQL engine so we don't set it
        self.name = name

    def json(self):
        return {'name': self.name}

    def save_to_db(self):
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self):
        db.session.delete(self)
        db.session.commit()

    @classmethod
    def find_by_name(cls, name):
        return cls.query.filter_by(name=name).first() # SELECT * FROM devices WHERE name=name LIMIT 1

    @classmethod
    def find_by_id(cls, _id):
        return cls.query.filter_by(id=_id).first()
